scrape_configs:
  - job_name: prometheus
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
#      - targets: ['localhost:8080']
      - targets: ['host.docker.internal:9090']