scrape_configs:
  - job_name: prometheus
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
#      - targets: ['host.docker.internal:9090']
      - targets: ['http://15.164.221.170:9090']