spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: db, server, firebase, slack, monitor
  jackson:
    serialization:
      indent-output: true

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : method
#    doc-expansion : none
