spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://localhost:3306/weteam?serverTimezone=Asia/Seoul
    #    username: root
    #    password: 1111
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      indent-output: true

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : method
#    doc-expansion : none

server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

firebase:
  database-url: ${FIREBASE_URL}

webhook:
  slack:
    url: ${SLACK_URL}